### ISSUE TITLE
Lib for making HTTP requests

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/nyts#12]
I'm leaning towards `axios` as I've worked with it before and it seems to work fine. Another plus is that it's 100% promise-based, and that works well with the idea behind `nyts` &mdash; a promise-based wrapper for the YTS API.

**Comment by yeskunall** [comment]
Sindre's [`got`](https://github.com/sindresorhus/got) isn't too bad either.

**Comment by yeskunall** [comment]
@arungalva what do you think? 🤔

**Comment by arungalva** [comment]
using Axios sounds good to me.

- Mature [X] 
- Used it before [X]
- promise-based [X]
- only 2 dependencies

**Comment by yeskunall** [comment]
Tracking with #24.

**Comment by yeskunall** [comment]
Merged #24.

/cc @arungalva works just fine. Just need to add some decent tests. Thanks for the suggestion! 👍
