### ISSUE TITLE
Move host URL from all the endpoints

### ISSUE THREAD

**Issue by arungalva** [yeskunall/nyts#16]
In the endpoints file [Here](https://github.com/yeskunall/nyts/blob/3d3c213f244a87b9d8e4c39119b1a45d6135f626/lib/endpoints.js), we could strip out the host and the version part of the url.

So the file could look something like this
```
const API_ENDPOINT = https://yts.ag/api/v2
module.exports = {
  COMMENT_ADD: '${API_ENDPOINT}/make_comment.json',
  COMMENT_DELETE: '${API_ENDPOINT}/delete_comment.json'
}
```
Either that or the API_ENDPOINT can be added at the level where we make the actual network requests.

This way, if yts gets v3 for their api, we don't have to change the url in a lot of places

**Comment by yeskunall** [comment]
I know ESLint will throw an error, but just in case you haven't noticed it yet, template literals must be wrapped in back-ticks. Feel free to make a PR.

**Comment by arungalva** [comment]
Yeah lol just copy pasted from the other comment to didn't fix that back-ticks
